# Generated by Django 2.0.2 on 2018-07-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0006_auto_20180727_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='age',
            field=models.IntegerField(default=25, verbose_name='年龄'),
        ),
    ]
