# Generated by Django 2.0.2 on 2018-07-28 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_course_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='tags',
            new_name='tag',
        ),
    ]
