# Generated by Django 2.0.2 on 2018-07-28 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='url',
            field=models.CharField(default='https://www.imooc.com/learn/943', max_length=200, verbose_name='访问地址'),
        ),
    ]
