# Generated by Django 2.0.2 on 2018-07-28 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20180728_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='learn_times',
            field=models.IntegerField(default=20, verbose_name='学习时长(分钟数)'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learn_times',
            field=models.IntegerField(default=100, verbose_name='学习时长(小时数)'),
        ),
    ]
